Add Image(s)::save() and deprecate export()
softprops/shiplift pull request #258
Opened 2021-02-07 23:01 UTC by elihunter173

## What did you implement:

I renamed `Image::export()` to `Image::save()` and did the same for `Images` to make their naming inline with the [Go API](https://pkg.go.dev/github.com/docker/docker/client#Client.ImageSave) and the docker CLI.

I discovered an old issue #184 that mentions this and I tend to agree that it would be good to use consistent terminology.

Closes: #184 

## How did you verify your change:

Ran tests locally.

## What (if anything) would need to be called out in the CHANGELOG for the next release:

Mention that `Image(s)::export()` has been deprecated in favor of `Image(s)::save()`. (Already done.)

2021-02-08 16:36 UTC, elihunter173 commented
Just realized that I made a typo in one of the return types. Should compile and pass all tests again.

2021-02-11 18:18 UTC, wojciechkepka approved these changes

2021-04-09 07:19 UTC, matthiasbeyer commented on CHANGELOG.md
> +* add Image(s)::save() and deprecate Image(s)::export() [#257](https://github.com/softprops/shiplift/pull/257)
I guess this has to be in the changelog section for the next release, not the existing one, right? :laughing:

2021-04-09 07:22 UTC, matthiasbeyer requested changes
Looks good in general.

Just a quick question: We're deprecating functions only on master and delete them before the release in this crate, is that correct? Because I'd imagine that we rather deprecate, release, then remove and make them gone in one release further. So the deprecation would remove them _after_ the 0.8.0 release.

I'm fine either way, just confused why it is done this way and not the other.

2021-04-09 07:22 UTC, matthiasbeyer commented on CHANGELOG.md
> +* add Image(s)::save() and deprecate Image(s)::export() [#257](https://github.com/softprops/shiplift/pull/257)
I guess this have to be in the changelog for the next one, not for the existing one, right? :laughing:

2023-07-27 20:00 UTC, closed without merging